export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const ADD_TRACKER = 'ADD_TRACKER';
export const LOGOUT = 'LOGOUT';
export const GEODATA_SUCCESS = 'GEODATA_SUCCESS';